spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/plantastoni}
spring.datasource.username=${DATABASE_USERNAME:plantastoni}
spring.datasource.password=${DATABASE_PASSWORD:plantastoni}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
